mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.apps import apps
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('books/', include(('bookstore.urls', 'bookstore'), namespace='books')),
    path('oscar/', include(apps.get_app_config('oscar').urls[0])),
    path('captcha/', include('captcha.urls')),

    re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

mysite/polls/urls.py
from django.urls import path

from . import views

# 命名空间方法2 app_name = 'polls'
urlpatterns = [
    path('index', views.entry_list, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('search', views.search, name='search'),
    # ajax
    path('banner', views.show_banner, name='banner'),
    path('banner_ajax', views.banner_ajax, name='banner_ajax'),
    # websocket
    path('banner_ws', views.show_banner_ws, name='banner_ws'),

    path('', views.set_cookie, name='set_cookie'),
]

mysite/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path('', register, name='register'),
    path('login.html', login_re, name='login'),
    path('logout.html', logout_re, name='logout'),
    path('change_ps.html', change_ps, name='change_password'),
    path('find_ps.html', find_ps, name='find_password'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/templates/base.html
<!doctype html>
{% load static %}
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="SHORTCUT ICON" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% block link %}{% endblock %}
</head>

<div>
    <header>公正投票</header>
</div>

{% if user.is_authenticated %}
    <span> Hello,{{ user.username }}已登录</span>
    <br>
    <a href="{% url 'user:logout' %}">退出登录</a>
    <br>
    <a href="{% url 'user:change_password' %}">修改密码</a>
{% else %}
    <span > Hello, 陌生人，您未登录 </span>
    <a href="{% url 'user:login' %}">点这里登录</a>
    <br>
    <a href="{% url 'polls:index' %}">不想登录或注册，随便看看</a>
{% endif %}

<br>
<a href="{% url 'user:register' %}">注册</a> <br>

<body>
{% block body %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-Lge2E2XotzMiwH69/MXB72yLpwyENMiOKX8zS8Qo7LDCvaBIWGL+GlRQEKIpYR04" crossorigin="anonymous"></script>
</body>

{% block js %}{% endblock %}

<div>
    <footer>© 2023 zhangdanying. All rights reserved.</footer>
</div>

</html>