mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.apps import apps
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('', include(('user.urls', 'user'), namespace='user')),
    path('books/', include(('bookstore.urls', 'bookstore'), namespace='books')),
    path('oscar/', include(apps.get_app_config('oscar').urls[0])),
    path('captcha/', include('captcha.urls')),

    re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
]

mysite/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path('', register, name='register'),
    path('login.html', login_re, name='login'),
    path('logout.html', logout_re, name='logout'),
    path('change_ps.html', change_ps, name='change_password'),
    path('find_ps.html', find_ps, name='find_password'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    qq = models.CharField('QQ号码', max_length=16, blank=True, null=True)
    weChat = models.CharField('微信账号', max_length=100, blank=True, null=True)
    mobile = models.CharField('手机号码', max_length=11, blank=True, null=True)
    # blank=True, null=True代表可以不填写，不填写的时候设置为空值

    # 设置返回值
    def __str__(self):
        return self.username

mysite/user/views.py
from django.shortcuts import render, redirect
from django.shortcuts import reverse
from .form import *
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import QueryDict


# 使用表单实现用户注册
def register(request):
    if request.method == 'POST':
        user = MyUserCreationForm(request.POST)
        if user.is_valid():
            user.save()
            return redirect(reverse('user:login'))
    else:
        user = MyUserCreationForm()
    return render(request, 'user/user.html', {'user': user})


# 用户登录
def login_re(request):
    tips = '请登录'
    user_login = True
    if request.method == 'POST':
        u = request.POST.get('username', '')
        p = request.POST.get('password1', '')

        # 摘取验证码表单
        query_dict = QueryDict(mutable=True)
        query_dict['captcha_1'] = request.POST.get('captcha_1')
        query_dict['captcha_0'] = request.POST.get('captcha_0')
        captcha_form = CaptchaForm(query_dict)

        if MyUser.objects.filter(username=u):
            user = authenticate(username=u, password=p)
            if user:
                if user.is_active:
                    if captcha_form.is_valid():
                        # 登录当前用户
                        login(request, user)
                        return redirect(reverse('polls:index'))
                    else:
                        tips = "验证码错误，请重新输入"
                else:
                    tips = '账号失效，请联系管理员'
            else:
                tips = '账号密码错误，请重新输入'
        else:
            tips = '用户不存在，请注册'
    user = MyUserCreationForm()
    return render(request, 'user/user.html', {'tips': tips, 'user_login':  user_login, 'user': user})


# 退出登录
def logout_re(request):
    logout(request)
    return redirect(reverse('user:login'))


@login_required(login_url='/login.html')
def change_ps(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)   # dont logout the user.
            messages.success(request, "Password changed.")
            return redirect(reverse('polls:index'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "user/change_password.html", {'form': form})


def find_ps(request):
    if request.POST:
        form = MyPasswordResetForm(request.POST)
        if form.is_valid():
            try:
                form.save(domain_override=request.get_host(),
                          email_template_name="user/password_reset_email.txt",
                          from_email=settings.EMAIL_HOST_USER, request=request)
                messages.success(request, '重设密码的链接已经发送到您的邮箱')
            except Exception as e:
                print(e)
                messages.error(request, "Email sending failed. Please try again.")
            return redirect(reverse('user:login'))
    else:
        form = MyPasswordResetForm()
    return render(request, "user/find_password.html", {'form': form})

mysite/user/templates/user/change_password.html
{% extends "base.html"  %}
{% load static %}
{% block title %}修改密码{% endblock %}
{% block link %}<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">{% endblock %}

{% block body %}
<div class="flex-center">
    <div class="container">
    <div class="flex-center">
    <div class="unit-1-2 unit-1-on-mobile">
            <h1>更改密码</h1>
        <form class="form" action="" method="post">
            {% csrf_token %}
            <div>旧密码:{{ form.old_password }}</div><div style="color:#F00">{{ form.old_password.errors }}</div>
            <div>新密码:{{ form.new_password1 }}</div><div style="color:#F00">{{ form.new_password1.errors }}</div>
            <div>新密码确认:{{ form.new_password2 }}</div><div style="color:#F00">{{ form.new_password2.errors }}</div>
            <button type="submit" class="btn btn-primary btn-block">提 交</button>
        </form>
    </div>
    </div>
    </div>
</div>
{% endblock %}

mysite/user/templates/user/find_password.html
{% extends "base.html"  %}
{% load static %}
{% block title %}找回密码{% endblock %}
{% block link %}<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">{% endblock %}

{% block body %}
<div class="flex-center">
    <div class="container">
    <div class="flex-center">
    <div class="unit-1-2 unit-1-on-mobile">
            <h1>找回密码</h1>
        <form class="form" action="" method="post">
            {% csrf_token %}
            <div>邮箱:{{ form.email }}</div><div style="color:#F00">{{ form.email.errors }}</div>
            <button type="submit" class="btn btn-primary btn-block">提 交</button>
        </form>
    </div>
    </div>
    </div>
</div>
{% endblock %}

mysite/user/templates/user/password_reset_complete.html
{% extends 'base.html' %}

{% block body %}

    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'user:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

mysite/user/templates/user/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}Enter new password{% endblock %}

{% block body %}

{% if validlink %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Change my password">
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}
{% endblock %}

mysite/user/templates/user/password_reset_done.html
{% extends 'base.html' %}

{% block body %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}

mysite/user/templates/user/user.html
{% extends "base.html"  %}
{% load static %}
{% block title %}用户管理{% endblock %}
{% block link %}<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">{% endblock %}

{% block body %}
<body>
<div class="flex-center">
    <div class="container">
    <div class="flex-center">
    <div class="unit-1-2 unit-1-on-mobile">
        {% if user_login %}
            <div><h1>用户登录</h1>
            {% if messages %}
                {% for message in messages %}
                {{ message }}
            {% endfor %}</div>
            {% endif %}
        {% else %}
            <h1>用户注册</h1>
        {% endif %}
        {% if tips %}
            <div style="color:#F00">{{ tips }}</div>
        {% endif %}
        <form class="form" action="" method="post">
            {% csrf_token %}
            <div>用户名:{{ user.username }}</div><div style="color:#F00">{{ user.username.errors }}</div>
            <div>密  码:{{ user.password1 }}</div><div style="color:#F00">{{ user.password1.errors }}</div>
            {% if user_login %}
            <div><a href="{% url 'user:find_password' %}">忘记密码?</a></div>
            {% else %}
            <div>密码确认:{{ user.password2 }}</div><div style="color:#F00">{{ user.password2.errors }}</div>
            <div>邮  箱(用于找回密码):{{ user.email }}</div><div style="color:#F00">{{ user.email.errors }}</div>
            <div>(选填)手机号:{{ user.mobile }}</div>
            <div>(选填)Q Q 号:{{ user.qq }}</div>
            <div>(选填)微信号:{{ user.weChat }}</div>
            {% endif %}
            <div>验证码:{{ user.captcha }}</div><div style="color:#F00">{{ user.captcha.errors }}</div>(点击图片换一张)
            <button type="submit" class="btn btn-primary btn-block">提 交</button>
        </form>
    </div>
    </div>
    </div>
</div>
</body>
{% endblock %}

{% block js %}
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_0').val(result['key'])
                });
        });
    })
</script>
{% endblock %}